### PR TITLE
Add build stack step

### PR DESCRIPTION
**Pull request by jneira**
* To check the stack.yaml does not go out of sync (see #395)

### CODE REVIEW

**Comment by jneira** [comment]
This needs a dedicated cache to make it faster

**Comment by jneira** [comment]
let's see if the prev pr fixed the build

**Comment by michaelpj** [comment]
Are any of our contributors using stack? We could just drop it, since it's only really useful for dev I guess.

**Review by michaelpj — APPROVED** [review]

**Comment by jneira** [comment]
> Are any of our contributors using stack? We could just drop it, since it's only really useful for dev I guess.

well at least @daquexian tried it 🙂

and I think it could be seen the other way  around: if we keep a working stack.yaml we will have more chances of having a contributor using stack

**Pull request merged**
