### PR TITLE
Update GHC build matrix

### PR DESCRIPTION
**Pull request by michaelpj**
Update to be in line with HLS, except with only one 8.10 version.
Maybe we could get rid of even more, but good to match HLS.

### CODE REVIEW

**Review by jneira — APPROVED** [review]
lgtm, thanks again

**Comment by michaelpj** [comment]
@jneira can you change the branch protection settings since the set of required checks is different now :pray:

**Comment by jneira** [comment]
> @jneira can you change the branch protection settings since the set of required checks is different now 🙏

you should have the rights to do it now 😄

**Comment by michaelpj** [comment]
Done.

**Pull request merged**
