### PR TITLE
WIP: Try to extend CI to 9.2.1

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by michaelpj** [comment]
Looks like we're blocked on at least:
- https://github.com/obsidiansystems/dependent-sum/issues/66
- https://github.com/obsidiansystems/constraints-extras/issues/45

**Comment by michaelpj** [comment]
I've pulled out the bounds changes to another PR, but this won't work for a bit.

**Comment by Ailrun** [comment]
@michaelpj For `constraint-extras`, it looks like their HEAD already supports GHC 9.2, but the actual release haven't been cut yet. (At least their CI works: https://github.com/obsidiansystems/constraints-extras/runs/4389445166?check_suite_focus=true)

**Comment by Bodigrim** [comment]
Looking at this and similar tickets for HLS, it seems that `dependent-map` subtree (`dependent-sum`, `constraints-extras`, `dependent-sum-template`, `th-extras`) causes constant delays, is it? Could it be replaced with `typerep-map`? Or maybe roll out a hand-written implementation of a type, isomorphic to `DMap SMethod`?

**Comment by michaelpj** [comment]
Yes, I think that's a good suggestion. I'd wondered about doing that, but I don't currently have a handle on how it's used. I'll take a look at what you suggested.

**Comment by michaelpj** [comment]
Removing `dependent-sum` and friends isn't trivial. We use `GEq` in a few places apart from the dependent map in `lsp`, and while we could just depend on `some` to get `GEq`, I really wouldn't want to write the instances by hand (big datatypes!), which pushes us back into the arms of `dependent-sum-template`.

**Comment by michaelpj** [comment]
Okay, now I think it's worth having a look at whether we can indeed get rid of `dependent-map`. It seems that we use it "properly" in a way that can't be obviously replaced by `typerep-map`. So hand-rolling a simple alternative might be the way to go.

**Comment by jneira** [comment]
> Okay, now I think it's worth having a look at whether we can indeed get rid of `dependent-map`. It seems that we use it "properly" in a way that can't be obviously replaced by `typerep-map`. So hand-rolling a simple alternative might be the way to go.

we could leverage changes in lsp? or hls ones are highly unrelated with?

**Comment by michaelpj** [comment]
I don't think I could get *rid* of the usage in `lsp`, or at least I don't understand it enough to say yet. So easier to replace the datastructure at the moment.

**Comment by michaelpj** [comment]
Done in https://github.com/haskell/lsp/pull/384

**Pull request closed without merging**
